### ISSUE TITLE
[Bug] main: 11 agent inline-task tests fail after merging PR-0c and PR-1 (stale AIService stub)

### ISSUE THREAD

**Issue by andyhsu6** [andyhsu6/AIFictionForge#86]
## Summary
`main` is red: 11 tests in `backend/tests/test_project_agent_inline_task.py` fail deterministically (770 passed + 11 failed = 781 collected).

## Repro
```bash
cd backend && .venv/bin/python -m pytest tests/test_project_agent_inline_task.py -q
```
- Expected: 14 passed.
- Actual: 11 failed, 3 passed.

## Root cause
PR-1's test stub predates PR-0c's budget gate. `make_service()` builds `ai_service=SimpleNamespace(default_model="test-model")`, but `stream_chat` now routes history budgeting through `agent_prompt_budget.resolve_history_budget_chars()`, which calls `AIService.resolve_effective_window_tokens()` (ensure-then-read gate).

First failure evidence:
```
>       effective_tokens = await ai_service.resolve_effective_window_tokens(
E       AttributeError: 'types.SimpleNamespace' object has no attribute 'resolve_effective_window_tokens'
app/services/agent_prompt_budget.py:158: AttributeError
```
Both PR branches merged green individually because each branch's suite never ran the other's tests.

## Fix
Test-side only: expose an async `resolve_effective_window_tokens(model=None, provider=None) -> 1_000_000` on the stub in `make_service()`, same shape as the established stubs in `tests/test_agent_prompt_budget.py` (`bare_service` / `_answer_only_ai_service`). No production code change.

## Acceptance
- Target file: 14 passed.
- Full backend suite: 781 passed, 0 failed.

---
（中文简述：PR-1 的测试桩早于 PR-0c 的预算门禁，桩上缺少 `resolve_effective_window_tokens`；仅修测试桩，不动生产代码。）
